version: '3.8'

services:
  app:
    container_name: cinepik-recommendation-engine
    build: .
    ports:
      - ${PORT:-3003}:${PORT:-3003}
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - cinepik-network

networks:
  cinepik-network:
    name: cinepik-network
    external: true
