apiVersion: v1
kind: Service
metadata:
  name: cinepik-recommendation-engine
spec:
  type: ClusterIP
  ports:
    - port: 3003
      protocol: TCP
      targetPort: 3003
  selector:
    app: cinepik-recommendation-engine
