apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinepik-recommendation-engine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinepik-recommendation-engine
  template:
    metadata:
      labels:
        app: cinepik-recommendation-engine
    spec:
      containers:
        - image: sebam/cinepik-recommendation-engine:latest
          name: cinepik-recommendation-engine
          env:
            - name: NODE_PORT
              value: '3003'
            - name: WATCH_THIS_RAPID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: recommendation-credentials
                  key: WATCH_THIS_RAPID_API_KEY
          ports:
            - containerPort: 3003
